version: '3'
services:
  nginx:
   container_name: some-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - app
   - account-ms

  app:
    container_name: app
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    expose:
      - "8080"
    command: mvn clean spring-boot:run
  
  account-ms:
    container_name: account-ms
    image: arunksalian/account-ms:0.0.6-SNAPSHOT
    restart: always
    expose:
        - "8090"
    command: mvn clean spring-boot:run
  redis-host:
    container_name: redis-host
    image: redis:6.2.4
    restart: always
  

